# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      addresses:
      - 192.168.1.168/24
      nameservers:
        addresses:
        - 8.8.8.8
        - 8.8.4.4
        - 8.8.8.8
        - 8.8.4.4
        search: []
      routes:
      - to: default
        via: 192.168.1.1
    enp0s8:
      addresses:
      - 192.168.2.1/24
  version: 2
